In [38]:
import numpy as np

In [39]:
dataset = np.array([1, 5, 10, 10, 17, 20, 35])


In [40]:
def bootstrap_sample(data):
    n = len(data)
    idx = np.arange(n)
    bs_idx = np.random.choice(idx, size=n, replace=True)
    return data[bs_idx]

In [41]:
bsms = []
for i in range(5):
    bs_sample = bootstrap_sample(dataset)
    bs_mean = np.mean(bs_sample)
    bsms.append(bs_mean)
    print(bs_sample, "{:5.2f}".format(bs_mean))

print("{:5.2f}".format(sum(bsms)/len(bsms)))

[10 17  5 20 17 17 35] 17.29
[ 5 20 10 20 35 10 10] 15.71
[10  5  1 17 35 10 10] 12.57
[10 10 17  5 17 10 10] 11.29
[10 35 10 20 17  1  1] 13.43
14.06
