# One Hot Encoder

[One Hot encoder](https://www.geeksforgeeks.org/machine-learning/ml-one-hot-encoding/)

In [75]:
from sklearn import datasets
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd

In [76]:
iris = datasets.load_iris()

In [77]:
iris.feature_names = [fn[:-5] for fn in iris.feature_names]

In [78]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['spicies'] = iris.target_names[iris.target]
iris_df.head()

,sepal length,sepal width,petal length,petal width,spicies
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [79]:
print(iris.target[[0, 50, 100]])

[0 1 2]


In [80]:
sparse = OneHotEncoder().fit_transform(iris.target.reshape(-1, 1))
print(sparse[[0, 1, 50, 51, 100, 101]].todense(), sep='\n')

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


One Hot Encoder metoda se može izvršiti i pomoću Pandasa. Detalji na [One Hot Encoding](https://www.geeksforgeeks.org/machine-learning/ml-one-hot-encoding/).

In [81]:
encoded = pd.get_dummies(iris_df, prefix='is')
print(encoded.iloc[[0, 1, 50, 51, 100, 101]])

     sepal length  sepal width  petal length  petal width  is_setosa  \
0             5.1          3.5           1.4          0.2       True   
1             4.9          3.0           1.4          0.2       True   
50            7.0          3.2           4.7          1.4      False   
51            6.4          3.2           4.5          1.5      False   
100           6.3          3.3           6.0          2.5      False   
101           5.8          2.7           5.1          1.9      False   

     is_versicolor  is_virginica  
0            False         False  
1            False         False  
50            True         False  
51            True         False  
100          False          True  
101          False          True  


In [82]:
X = encoded.drop(columns=['petal length'])
y = encoded['petal length']

In [83]:
(features_train, features_test, target_train, target_test) = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)
algorithm = LinearRegression()
model = algorithm.fit(features_train, target_train)
predictions = model.predict(features_test)

mse = mean_squared_error(target_test, predictions)
r2 = model.score(features_test, target_test)
print('MSE: %.3f' % mse)
print('R2: %.3f' % r2)

MSE: 0.037
R2: 0.947


Izbacivanje columna

In [84]:
df = pd.DataFrame({
    'grad': ['Zagreb', 'Split', 'Rijeka'],
    'cijena': [100, 120, 90]
})
X = df[['grad']]
y = df[['cijena']]

In [85]:
ohe = OneHotEncoder(drop='first', sparse_output=False)
Z = ohe.fit_transform(X)
print(Z)

[[0. 1.]
 [1. 0.]
 [0. 0.]]


In [86]:
lr = LinearRegression()
model_lr = lr.fit(Z, y)

print('Coef', model_lr.coef_)
print('Intercept', model_lr.intercept_)

Coef [[30. 10.]]
Intercept [90.]
